language: java
jdk: oraclejdk8

before_install:
- "sed -i \"s/^\\(version:.*\\)/\\1.0.$TRAVIS_BUILD_NUMBER/\" src/main/resources/plugin.yml"
- pushd ~/build/
- git clone --depth=1 https://github.com/NyaaCat/NyaaCore NyaaCat/NyaaCore
- export NYAACORE_LANG_DIR=`readlink -f ./NyaaCat/NyaaCore/src/main/resources/lang/`
- popd
after_success:
- 'cp build/libs/HamsterEcoHelper.jar ./HamsterEcoHelper-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar'
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER
- export GIT_ORIGIN_URL=`git config --get remote.origin.url`
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GITHUB_KEY:@github.com" > .git/credentials
- git status
- git push origin HEAD:$TRAVIS_BRANCH -q --follow-tags
- gem install octokit -v 4.3.0
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true
  api_key:
    secure: "SeL38ow6S9AvTmxR1xugzDemmAMpxJ35XgLaEnyyZN+f6N/bmCCKKrabpAe9ntOIZAJapfIb2TTR5zyJ2GGuasnIEZ5hqGKCqy+sN4Y/M5JHcjeZRghw8iYx+hQzPWSayln9lJUkiL31zfw4CFVjqPWCv5ejr1bysq6vMSQG4NsgSdnB36vMLCpKtgrgdE+COACYJ7Zp/OFoU+aAZMaeWF8KVFjwfjnJwdYlxwnPrQ9qIfz094RA0ZwkX77BvA3QdpRei1yw6rhp/CeRsUSry/P+P0GSiwFnhuEX2Npqzs89bdQeipx9gJT/0EsNtAk6MOvxOJt9Ykk44OwPLZ/UOXhhA3ZqQGZEdx7jWjJBBRFVfOP8oI6zY+ux0vfHucS10yJ00ErzkoQaGn0YnguOO9Bs++XC/BXnEoMYb6M9re9UDZy6SbMO41oW4xKVHgPNS1ebGmFoEEm5FoGXBhVF5vn66nwWNYtheDLwX06CF3tP1T21D3b6bLATvzLEpYV6Zv3I7DDkAECltLKZaMHMxr5g/7DrvbNnawLR04WDzH4a4+OvoJwhxmUIEJ6bUStjVBfIHTcWmSHyDrg2HeMJrN2SMD4OiXGGjGGnaOhvU6r+95AgAfDrL1vy5vdjB8seQ2f/UGJwSNQH7OWcZUhxfxBP0yBif2GdlMhieDdaHBA="
  file: ./HamsterEcoHelper-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar
  on:
    tags: false

branches:
  except:
  - "/^*-v[0-9]/"

env:
  global:
  - secure: "O56CEunSuLO/d1ccLJmNJTlweReZ/tVgDzeTAIYVJBsel0IVBd91um+3Up1GuUvhyXGZHLdXBunsYGWL2tI1HzM7MkqWcnUDGHCzR8sh65aOAR486btZTcmlvUe7LzqmxP4CGPQLa1CcwqisCaYf3+R6u0lbYhq+Ujq0Db3DAbExUBo5gHaaXnCRpHBmNyeibcfTOVHRmUZLmfmYfcuXbaMwQ8ySRK7lo3rqIiJMkowe0q07vfcZRTNNP8fClaY8z6RmZuvoclHN1L+PIIXG0OS9yIkAdUmtu78ib/GpHhOUPjHMtHjYSWg36W1WCnZR7qjQMY2ZS2RR50C3ajwFjzIH+6jok7GUvVodPvc1/kyO3NkIvYmyhZDocn13ArohrrVQxhjBR5a80cKIq45GA0skemLBOWq3nqPvzS50YDZhns1uaaPhLScCG7HYJIHFdw0kx4FPq8iVk+U780J/5sfJMKR8tbVzQJt0FSzS1AYYqFFvAVf5pTcdltXsHxLlp/TUi8BErmZK4fw2drdc9UyzjtN1O98Ul2KBhrFRtxbGjN3RAXRy3RJSW50HRFMc7L+e+qMpQ5t+yDRiobVXI3ZW+ERvoWHyd9Wiq2pkBHYq2WZwsM4rujkmb3XcKwSlZqDtQ0zk/ZSIUoXhLSUfhAEfijdcTnGd5dR3N/L7/oI="
  - main_version=3
  - trigger_ci=20170624
